[package]
name = "aoc"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.35"
fnv = "1.0.7"
hex = "0.4.2"
itertools = "0.9.0"
maplit = "1.0.2"
md-5 = "0.9.1"
rayon = "1.5.0"
thiserror = "1.0.22"

[dev-dependencies]
criterion = "0.3.3"
indoc = "1.0.3"

[[bench]]
name = "year2020"
harness = false

[[bench]]
name = "year2019"
harness = false

[[bench]]
name = "year2018"
harness = false

[[bench]]
name = "year2017"
harness = false

[[bench]]
name = "year2016"
harness = false

[[bench]]
name = "year2015"
harness = false
