[package]
name = "aoc"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.26"
fnv = "1.0.6"
itertools = "0.8.2"
maplit = "1.0.2"
thiserror = "1.0.9"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "year2019"
harness = false

[[bench]]
name = "year2018"
harness = false

[[bench]]
name = "year2017"
harness = false
